### ISSUE TITLE
'description' field of attribute is not displayed when form is being used in OSM contributor

### ISSUE THREAD

**Issue by pdfext** [jawg/h2geo-presets#27]
Hello
 The 'description' is set in the indication_board.yml but I cannot see this description when the form is displayed in OSM contributor. The only thing which is displayed when we are being using the form of OSM contributor is the value of 'key' of the attribute, or the values set in 'values', but the 'description' is not dislayed. 
Can you see if there is something wrong ?
 Thank you in advance

**Comment by loicortola** [comment]
Hi @pdfext, I just noticed that this issue is on the wrong repository.
Please post it on the repository of [osm-contributor](https://github.com/jawg/osm-contributor).
