### ISSUE TITLE
'query' is not implemented and it is a pity : 'query' are really missing to have OSM contributor functional

### ISSUE THREAD

**Issue by pdfext** [jawg/h2geo-presets#28]
Hello
 I ve tried to use the  'query'. This is documented this way in the spec :
 **$.groups.$.item.$.query 
The overpass query allowing to fetch the current item. This field is optional.**
This is quite short and not very self explainable  !
The query I wish is the following   
**[out:json][timeout:25];(node["advertising"="board"]["legal_type:FR"="préenseigne"]({{bbox}}););out body;** 
I note for information, that for dynamic umap, query are like this one :+1: 
**http://overpass-api.de/api/interpreter?data=[out:json][timeout:25];(node["advertising"="board"]["legal_type:FR"="préenseigne"]({south},{west},{north},{east}););out body;**

I ve tried several query syntaxes, none worked well. LOrtola conformed later that the 'query' is in fact not implemented.  The query is needed anyhow to know if the object when want to set and add in OSM already exists or not. If it does already exist, there is obviously no need to add it again in OSM, but user of OSM contributor needs to know that !

Thank you to see if this 'query' can be added in implementation !

**Comment by loicortola** [comment]
Hi @pdfext, I just noticed that this issue is on the wrong repository.
Please post it on the repository of [osm-contributor](https://github.com/jawg/osm-contributor).
