### ISSUE TITLE
'constraints' does not seem to properly work

### ISSUE THREAD

**Issue by pdfext** [jawg/h2geo-presets#29]
Hello
 In indication_board.yml I have been using 'constraints', but with no effect
 As you can see, if 'message' is equal to 'other', then we should have  :
    legal_type:FR=publicité 
     legal_status:FR=illégal
But i have not seen these attributes properly set when used
Then I suppose there is something wrong into the implementation of 'constraints', or maybe this implementation is missing.
Can you have a look please ?
Thank you in advance

**Comment by loicortola** [comment]
Hi @pdfext, I just noticed that this issue is on the wrong repository.
Please post it on the repository of [osm-contributor](https://github.com/jawg/osm-contributor).
