### ISSUE TITLE
Localisation of attributes into form is not functional

### ISSUE THREAD

**Issue by pdfext** [jawg/h2geo-presets#31]
hello
 In indication_board.yml I have localised as much as I can attributes, and the defaults is always in French, but as a matter of fact, the only language which is displayed in English when this indication_board form is being used. The French is properly displayed before entering into the form, but into the form the language is English. So localisation is partly functional only.
 Can you see if the localisation of form can be added in implementation please ?
 Thank you in advance!

**Comment by loicortola** [comment]
Hi @pdfext, I just noticed that this issue is on the wrong repository.
Please post it on the repository of [osm-contributor](https://github.com/jawg/osm-contributor).

**Comment by loicortola** [comment]
Done
