### ISSUE TITLE
Data of profile (like version/description) are not visible when profile is being used in OSM contributor

### ISSUE THREAD

**Issue by pdfext** [jawg/h2geo-presets#32]
Hello
 More an improvement rather than a real issue.
 It could be interesting to be able to displayed the version and the description of the profile. These info are set into the yml file.
 It is something minor
Thank you in advance

**Comment by loicortola** [comment]
Hi @pdfext, I just noticed that this issue is on the wrong repository.
Please post it on the repository of [osm-contributor](https://github.com/jawg/osm-contributor).

**Comment by loicortola** [comment]
Done
