### ISSUE TITLE
required=true has no real effect 

### ISSUE THREAD

**Issue by pdfext** [jawg/h2geo-presets#33]
hello 
 I have set required=true on some attributes of indication_board.yml  for example on 'land-property' which can take two values 'private' or 'public'. It means that the value should be either 'private' or 'public'. Required=true should mean that this attribute cannot be unset. But the form interface proposes the 'undefined' value, which means that this attribute can be unset. 
 Then I presume that the 'required=true' is not properly implemented (or maybe not implemented ?)
Than you to verify

**Comment by loicortola** [comment]
Hi @pdfext, I just noticed that this issue is on the wrong repository.
Please post it on the repository of [osm-contributor](https://github.com/jawg/osm-contributor).

**Comment by loicortola** [comment]
Done
