### ISSUE TITLE
API Enhancements

### ISSUE THREAD

**Issue by loicortola** [jawg/h2geo-presets#41]
From JungleBus Workshop:

- [x]  MapContrib needs to be able to add specific tags which are private (<=> aka would not be pushed to remote repository)
- [x] Street Complete associates a statement (question) with each tag. We need to be able to add the possibility of specifying statements for each tag. Needs to be i18nable.
- [x] Add the ability to support icons on : a type level and a tag level. Icons can be specified in three different ways: either using a URI (cf issue #39 ), a URL, or an asset. Icons can be internationalizable.
- [x] Add the COLOR tag type. Possible values are: CSS colors and hex (6 hex chars, 3 hex chars)

**Comment by PanierAvide** [comment]
* [x] In `$.groups.$.items.$.tags.$.validation`, add a `format` entry accepting `EMAIL` or `URL` values (which is roughly an alias for appropriate regular expression).

**Comment by loicortola** [comment]
Two new tag types: SINGLE_CHOICE_IMAGE MULTI_CHOICE_IMAGE,
one new tag value: images ==> cf spec

**Comment by GuillaumeAmat** [comment]
After a lot of discussions, we decided to remove the new `SINGLE_CHOICE_IMAGE` and  `MULTI_CHOICE_IMAGE` options. The `values` tag item is now still mandatory and the `images` item indicate that the choices have to be displayed with images.

**Comment by LeoFrachet** [comment]
Added transformations from URIs to URLs.

@GuillaumeAmat: I was unsure of which URLs to put for the local resources. I didn't put the full path for now. Depends how the API will serve the JSON and the resources. (https://github.com/jawg/h2geo-presets/commit/f85a53729bd0aa902276e2e238db4ee494ab43f7)

**Comment by loicortola** [comment]
@LeoFrachet got it.
If you take a look at deploy.sh it basically moves output resources to gh-pages branch and overrides the gh-pages branch (push force).
We would need to move the resources to gh-pages and serve them through it.
Do you want me to finish it?

**Comment by loicortola** [comment]
Done.
